/**
 * 图标索引文件
 * 自动生成 - 请勿手动修改
 */

export const ICONS = [
  'school',
  'menu_book',
  'psychology',
  'auto_stories',
  'workspace_premium',
  'emoji_events',
  'cast_for_education',
  'language',
  'view_in_ar',
  'code',
  'memory',
  'dns',
  'cloud',
  'security',
  'fingerprint',
  'data_usage',
  'api',
  'storage',
  'computer',
  'smartphone',
  'play_circle',
  'pause_circle',
  'volume_up',
  'videocam',
  'headphones',
  'radio',
  'photo_camera',
  'image',
  'music_note',
  'mic',
  'people',
  'person',
  'group',
  'forum',
  'chat',
  'email',
  'phone',
  'location_on',
  'share',
  'notifications',
  'home',
  'menu',
  'close',
  'arrow_forward',
  'arrow_back',
  'expand_more',
  'expand_less',
  'more_vert',
  'search',
  'refresh',
  'check_circle',
  'error',
  'warning',
  'info',
  'hourglass_empty',
  'schedule',
  'favorite',
  'star',
  'bookmark',
  'thumb_up',
  'add',
  'edit',
  'delete',
  'save',
  'download',
  'upload',
  'print',
  'file_download',
  'file_upload',
  'content_copy',
  'rocket',
  'trending_up',
  'analytics',
  'touch_app',
  'devices',
  'brush',
  'lightbulb',
  'shopping_cart',
  'payment',
  'local_offer',
];

export const ICON_PATHS = {
  school: 'assets/icons/outlined/school.svg',
  menu_book: 'assets/icons/outlined/menu_book.svg',
  psychology: 'assets/icons/outlined/psychology.svg',
  auto_stories: 'assets/icons/outlined/auto_stories.svg',
  workspace_premium: 'assets/icons/outlined/workspace_premium.svg',
  emoji_events: 'assets/icons/outlined/emoji_events.svg',
  cast_for_education: 'assets/icons/outlined/cast_for_education.svg',
  language: 'assets/icons/outlined/language.svg',
  view_in_ar: 'assets/icons/outlined/view_in_ar.svg',
  code: 'assets/icons/outlined/code.svg',
  memory: 'assets/icons/outlined/memory.svg',
  dns: 'assets/icons/outlined/dns.svg',
  cloud: 'assets/icons/outlined/cloud.svg',
  security: 'assets/icons/outlined/security.svg',
  fingerprint: 'assets/icons/outlined/fingerprint.svg',
  data_usage: 'assets/icons/outlined/data_usage.svg',
  api: 'assets/icons/outlined/api.svg',
  storage: 'assets/icons/outlined/storage.svg',
  computer: 'assets/icons/outlined/computer.svg',
  smartphone: 'assets/icons/outlined/smartphone.svg',
  play_circle: 'assets/icons/outlined/play_circle.svg',
  pause_circle: 'assets/icons/outlined/pause_circle.svg',
  volume_up: 'assets/icons/outlined/volume_up.svg',
  videocam: 'assets/icons/outlined/videocam.svg',
  headphones: 'assets/icons/outlined/headphones.svg',
  radio: 'assets/icons/outlined/radio.svg',
  photo_camera: 'assets/icons/outlined/photo_camera.svg',
  image: 'assets/icons/outlined/image.svg',
  music_note: 'assets/icons/outlined/music_note.svg',
  mic: 'assets/icons/outlined/mic.svg',
  people: 'assets/icons/outlined/people.svg',
  person: 'assets/icons/outlined/person.svg',
  group: 'assets/icons/outlined/group.svg',
  forum: 'assets/icons/outlined/forum.svg',
  chat: 'assets/icons/outlined/chat.svg',
  email: 'assets/icons/outlined/email.svg',
  phone: 'assets/icons/outlined/phone.svg',
  location_on: 'assets/icons/outlined/location_on.svg',
  share: 'assets/icons/outlined/share.svg',
  notifications: 'assets/icons/outlined/notifications.svg',
  home: 'assets/icons/outlined/home.svg',
  menu: 'assets/icons/outlined/menu.svg',
  close: 'assets/icons/outlined/close.svg',
  arrow_forward: 'assets/icons/outlined/arrow_forward.svg',
  arrow_back: 'assets/icons/outlined/arrow_back.svg',
  expand_more: 'assets/icons/outlined/expand_more.svg',
  expand_less: 'assets/icons/outlined/expand_less.svg',
  more_vert: 'assets/icons/outlined/more_vert.svg',
  search: 'assets/icons/outlined/search.svg',
  refresh: 'assets/icons/outlined/refresh.svg',
  check_circle: 'assets/icons/outlined/check_circle.svg',
  error: 'assets/icons/outlined/error.svg',
  warning: 'assets/icons/outlined/warning.svg',
  info: 'assets/icons/outlined/info.svg',
  hourglass_empty: 'assets/icons/outlined/hourglass_empty.svg',
  schedule: 'assets/icons/outlined/schedule.svg',
  favorite: 'assets/icons/outlined/favorite.svg',
  star: 'assets/icons/outlined/star.svg',
  bookmark: 'assets/icons/outlined/bookmark.svg',
  thumb_up: 'assets/icons/outlined/thumb_up.svg',
  add: 'assets/icons/outlined/add.svg',
  edit: 'assets/icons/outlined/edit.svg',
  delete: 'assets/icons/outlined/delete.svg',
  save: 'assets/icons/outlined/save.svg',
  download: 'assets/icons/outlined/download.svg',
  upload: 'assets/icons/outlined/upload.svg',
  print: 'assets/icons/outlined/print.svg',
  file_download: 'assets/icons/outlined/file_download.svg',
  file_upload: 'assets/icons/outlined/file_upload.svg',
  content_copy: 'assets/icons/outlined/content_copy.svg',
  rocket: 'assets/icons/outlined/rocket.svg',
  trending_up: 'assets/icons/outlined/trending_up.svg',
  analytics: 'assets/icons/outlined/analytics.svg',
  touch_app: 'assets/icons/outlined/touch_app.svg',
  devices: 'assets/icons/outlined/devices.svg',
  brush: 'assets/icons/outlined/brush.svg',
  lightbulb: 'assets/icons/outlined/lightbulb.svg',
  shopping_cart: 'assets/icons/outlined/shopping_cart.svg',
  payment: 'assets/icons/outlined/payment.svg',
  local_offer: 'assets/icons/outlined/local_offer.svg',
};

export function getIconPath(
  name: string,
  style: 'outlined' | 'round' | 'sharp' | 'twotone' = 'outlined'
): string {
  return `assets/icons/${style}/${name}.svg`;
}
