; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor options
monitor_speed = 115200

; Libraries
lib_deps = 
    tensorflow/tensorflow-lite-micro@^2.12.0
    earlephilhower/ESP8266Audio@^1.9.7
    bblanchon/ArduinoJson@^6.21.3
    h2zero/NimBLE-Arduino@^1.4.1

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DTF_LITE_STATIC_MEMORY
    -DTF_LITE_DISABLE_X86_NEON
    -O3

; Partition scheme for larger flash
board_build.partitions = huge_app.csv