"""
数据库模型包
"""

# 先导入基础模型（Organization, User 等）
from .license import (
    License,
    LicenseActivityLog,
    LicenseCreate,
    LicenseResponse,
    LicenseStatus,
    LicenseType,
    Organization as OrgPydantic,
    OrganizationCreate,
    OrganizationResponse,
    OrganizationUpdate,
)
# SQLAlchemy Organization 模型（必须在其他模型之前导入）
from .organization import Organization
from .user import User, UserRole

# 然后导入依赖基础模型的模型
from .classroom import (
    ClassSchedule,
    ClassScheduleCreate,
    ClassScheduleResponse,
    Classroom,
    ClassroomCreate,
    ClassroomResponse,
)
from .sponsorship import Sponsorship  # 赞助模型，必须在Organization之后导入
from .ai_request import AIRequest
from .ar_vr_content import (
    ARVRContent,
    ARVRContentCreate,
    ARVRContentResponse,
    ARVRContentType,
    ARVRContentUpdate,
    ARVRInteractionLog,
    ARVRPlatform,
    ARVRProgressTracking,
    ARVRSensorData,
    InteractionLogCreate,
    InteractionMode,
    ProgressTrackingCreate,
    ProgressTrackingResponse,
    SensorDataCreate,
    SensorDataResponse,
    SensorType,
)
from .content_store import (
    ContentAccessGrant,
    ContentAccessLog,
    ContentCategory,
    ContentItem,
    ContentRating,
    ContentReview,
    ContentStatus,
    ContentTag,
    ContentTagAssociation,
    ContentType,
    DRMContent,
    DRMStatus,
    Order,
    OrderItem,
    OrderStatus,
    ShoppingCartItem,
)
from .course_version import (
    BranchCreate,
    BranchResponse,
    CommitData,
    CourseSnapshot,
    CourseVersion,
    CourseVersionCreate,
    CourseVersionResponse,
    MergeRequest,
    MergeRequestCreate,
    MergeRequestResponse,
    VersionBranch,
    VersionChange,
)
from .dynamic_course import (
    BacktestResult,
    CourseComponentResponse,
    CourseGenerationLog,
    CourseGenerationStats,
    CourseQueryParams,
    DynamicCourseRequestCreate,
    DynamicCourseResponseDetail,
    GeneratedCourse,
    StudentProfileCreate,
    TemplateEvaluation,
)
from .hardware_certification import (
    BadgeConfig,
    BadgeStyle,
    CertificationRequest,
    CertificationResponse,
    CertificationStatus,
    HardwareCertificationDB,
    TestCategory,
    TestResult,
)
from .hardware_module import (
    DamageLevel,
    HardwareModule,
    HardwareModuleCreate,
    HardwareModuleResponse,
    HardwareModuleStatus,
    HardwareModuleUpdate,
    ModuleRentalRecord,
    ModuleRentalRecordResponse,
    ModuleRentalStatus,
    RentModuleRequest,
    ReturnModuleRequest,
)
from .learning_source import (
    LearningSource,
    LearningSourceCreate,
    LearningSourceListResponse,
    LearningSourceResponse,
    LearningSourceStatus,
    LearningSourceType,
    LearningSourceUpdate,
)
from .user_organization import (
    UserOrganization,
    UserOrganizationCreate,
    UserOrganizationListResponse,
    UserOrganizationResponse,
    UserOrganizationRole,
    UserOrganizationStatus,
    UserOrganizationUpdate,
)
from .unified_learning_record import (
    LearningRecordStatus,
    UnifiedLearningRecord,
    UnifiedLearningRecordCreate,
    UnifiedLearningRecordListResponse,
    UnifiedLearningRecordResponse,
    UnifiedLearningRecordUpdate,
    UnifiedProgressStats,
)
from .payment import (
    Order,
    OrderStatus,
    Payment,
    PaymentMethod,
    PaymentNotification,
    PaymentStatus,
    Product,
    ShoppingCart,
)
from .permission import (
    Permission,
    PermissionAction,
    PermissionCategory,
    PermissionLog,
    Role,
    UserRoleAssignment,
)
from .recommendation import (
    CourseFeature,
)
from .subscription import (
    BillingCycle,
    SubscriptionCycle,
    SubscriptionPayment,
    SubscriptionPlan,
    SubscriptionPlanType,
    SubscriptionStatus,
    UserSubscription,
)
from .subscription_fsm import (
    SubscriptionFSM,
    create_subscription_fsm,
    process_subscription_lifecycle,
)
from .unified_material import (
    UnifiedMaterial,
)
from .user_license import (
    AssignUserLicenseRequest,
    HardwareRentalSummary,
    TokenPackage,
    TokenPackageType,
    TokenRechargeRecord,
    TokenUsageRecord,
    UpdateUserLicenseRequest,
    UserLicense,
    UserLicenseResponse,
    UserLicenseStatus,
    UserTokenBalance,
)
from .student import (
    Student,
    StudentCreate,
    StudentResponse,
)
from .teacher import (
    Teacher,
    TeacherCreate,
    TeacherResponse,
)
from .finance import (
    FinancialTransaction,
    TransactionType,
    TransactionStatus,
    PaymentMethod,
    TuitionRecord,
    PaymentStatus,
    CoursePricing,
    PricingStrategy,
    TeacherSalary,
    SalaryStatus,
    CourseConsumption,
    ConsumptionType,
    ConsumptionStatus,
)

__all__ = [
    "User",
    "UserRole",
    "Permission",
    "Role",
    "UserRoleAssignment",
    "PermissionLog",
    "PermissionCategory",
    "PermissionAction",
    "AIRequest",
    "CourseFeature",
    "Payment",
    "Order",
    "Product",
    "ShoppingCart",
    "PaymentNotification",
    "PaymentMethod",
    "PaymentStatus",
    "OrderStatus",
    "SubscriptionPlan",
    "UserSubscription",
    "SubscriptionPayment",
    "SubscriptionCycle",
    "BillingCycle",
    "SubscriptionStatus",
    "SubscriptionPlanType",
    "SubscriptionFSM",
    "create_subscription_fsm",
    "process_subscription_lifecycle",
    "CertificationStatus",
    "TestCategory",
    "TestResult",
    "CertificationRequest",
    "CertificationResponse",
    "BadgeStyle",
    "BadgeConfig",
    "HardwareCertificationDB",
    "LicenseStatus",
    "LicenseType",
    "Organization",
    "License",
    "LicenseActivityLog",
    "OrganizationCreate",
    "OrganizationUpdate",
    "LicenseCreate",
    "LicenseResponse",
    "OrganizationResponse",
    "UserLicense",
    "UserLicenseStatus",
    "UserLicenseResponse",
    "UserTokenBalance",
    "TokenPackage",
    "TokenPackageType",
    "TokenRechargeRecord",
    "TokenUsageRecord",
    "AssignUserLicenseRequest",
    "UpdateUserLicenseRequest",
    "HardwareRentalSummary",
    # 课程模型
    "CourseVersion",
    "VersionBranch",
    "MergeRequest",
    "CourseSnapshot",
    "VersionChange",
    "CommitData",
    "CourseVersionCreate",
    "CourseVersionResponse",
    "BranchCreate",
    "BranchResponse",
    "MergeRequestCreate",
    "MergeRequestResponse",
    "ARVRContent",
    "ARVRSensorData",
    "ARVRInteractionLog",
    "ARVRProgressTracking",
    "ARVRContentType",
    "ARVRPlatform",
    "SensorType",
    "InteractionMode",
    "ARVRContentCreate",
    "ARVRContentUpdate",
    "ARVRContentResponse",
    "SensorDataCreate",
    "SensorDataResponse",
    "InteractionLogCreate",
    "ProgressTrackingCreate",
    "ProgressTrackingResponse",
    "ContentType",
    "ContentStatus",
    "ContentRating",
    "OrderStatus",
    "DRMStatus",
    "ContentCategory",
    "ContentTag",
    "ContentTagAssociation",
    "ContentItem",
    "ContentReview",
    "ShoppingCartItem",
    "Order",
    "OrderItem",
    "DRMContent",
    "ContentAccessGrant",
    "ContentAccessLog",
    "GeneratedCourse",
    "CourseGenerationLog",
    "StudentProfileCreate",
    "DynamicCourseRequestCreate",
    "CourseComponentResponse",
    "DynamicCourseResponseDetail",
    "CourseGenerationStats",
    "BacktestResult",
    "CourseQueryParams",
    "TemplateEvaluation",
    "HardwareModule",
    "ModuleRentalRecord",
    "HardwareModuleStatus",
    "ModuleRentalStatus",
    "DamageLevel",
    "HardwareModuleCreate",
    "HardwareModuleUpdate",
    "RentModuleRequest",
    "ReturnModuleRequest",
    "HardwareModuleResponse",
    "ModuleRentalRecordResponse",
    # 教室与课表模型
    "Classroom",
    "ClassroomCreate",
    "ClassroomResponse",
    "ClassSchedule",
    "ClassScheduleCreate",
    "ClassScheduleResponse",
    # 学生模型
    "Student",
    "StudentCreate",
    "StudentResponse",
    # 教师模型
    "Teacher",
    "TeacherCreate",
    "TeacherResponse",
    # 多来源学习关联模型
    "LearningSource",
    "LearningSourceType",
    "LearningSourceStatus",
    "LearningSourceCreate",
    "LearningSourceUpdate",
    "LearningSourceResponse",
    "LearningSourceListResponse",
    "UserOrganization",
    "UserOrganizationRole",
    "UserOrganizationStatus",
    "UserOrganizationCreate",
    "UserOrganizationUpdate",
    "UserOrganizationResponse",
    "UserOrganizationListResponse",
    "UnifiedLearningRecord",
    "LearningRecordStatus",
    "UnifiedLearningRecordCreate",
    "UnifiedLearningRecordUpdate",
    "UnifiedLearningRecordResponse",
    "UnifiedLearningRecordListResponse",
    "UnifiedProgressStats",
    # 财务管理模型
    "FinancialTransaction",
    "TransactionType",
    "TransactionStatus",
    "PaymentMethod",
    "TuitionRecord",
    "PaymentStatus",
    "CoursePricing",
    "PricingStrategy",
    "TeacherSalary",
    "SalaryStatus",
    "CourseConsumption",
    "ConsumptionType",
    "ConsumptionStatus",
    # 赞助模型
    "Sponsorship",
    # 统一课件库模型
    "UnifiedMaterial",
]
